# Rename this file to languages.toml to enable multilingual support
[en]
languageName = "English"
languagedirection = "ltr"
title = "Triccsr's Blog"
weight = 2
[zh-cn]
languageName = "简体中文"
languagedirection = "ltr"
title = "Triccsr的垃圾场"
weight = 1