baseURL = 'https://example.org/'
languageCode = 'en-us'
title = 'My New Hugo Site'
theme = 'hugo-theme-stack'
enableEmoji = true
timeout = '100s'

[markup.goldmark.parser.attribute]
block = true # default is false